/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/*
 * adlogin.java
 *
 * Created on Jul 10, 2017, 9:21:47 PM
 */

/**
 *
 * @author Santosh
 */
public class adlogin extends javax.swing.JFrame {

    /** Creates new form adlogin */
    public adlogin() {
        super("ADMIN LOGIN");
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("home.jpg")).getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aduserTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adpasTF = new javax.swing.JPasswordField();
        adloginBTN = new javax.swing.JButton();
        hmBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel1.setText("ADMIN LOGIN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("USERNAME");

        aduserTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aduserTFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("PASSWORD");

        adpasTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adpasTFActionPerformed(evt);
            }
        });

        adloginBTN.setText("Log In");
        adloginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adloginBTNActionPerformed(evt);
            }
        });

        hmBTN.setText("Home");
        hmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(186, 186, 186)
                            .addComponent(adloginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(hmBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(97, 97, 97)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(adpasTF, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(aduserTF)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(aduserTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adpasTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adloginBTN)
                    .addComponent(hmBTN))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmBTNActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_hmBTNActionPerformed

    private void adloginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adloginBTNActionPerformed
        // TODO add your handling code here:
        try{
        int flag=0;
        Connection conn=ConnectionProvider.getConnection();
        Statement stmt=conn.createStatement();
        ResultSet rs=stmt.executeQuery("Select * from admin");
        String aduser=aduserTF.getText();
        String pass=adpasTF.getText();
        while(rs.next())
        {
            String uuid=rs.getString("username");
            String ppwd=rs.getString("password");
            if(uuid.equals(aduser) && ppwd.equals(pass))
            {
                JOptionPane.showMessageDialog(null,"LOGIN SUCCESSFUL!!!!!");
                new admin().setVisible(true);
                this.setVisible(false);
                flag=1;
            }
        }
        if(flag==0)
        {
            JOptionPane.showMessageDialog(null,"LOGIN OR PASSWORD WRONG!! PLEASE TRY AGAIN");
                aduserTF.setText("");
                adpasTF.setText("");
        }
        rs.close();
        conn.close();
        stmt.close();
        }
        catch(Exception e)
                {
                JOptionPane.showMessageDialog(null,e);
                }
}//GEN-LAST:event_adloginBTNActionPerformed

    private void aduserTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aduserTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aduserTFActionPerformed

    private void adpasTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adpasTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adpasTFActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new adlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adloginBTN;
    private javax.swing.JPasswordField adpasTF;
    private javax.swing.JTextField aduserTF;
    private javax.swing.JButton hmBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
