
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * liblogin.java
 *
 * Created on Jul 10, 2017, 9:22:32 PM
 */

/**
 *
 * @author Santosh
 */
public class liblogin extends javax.swing.JFrame {

    /** Creates new form liblogin */
    public liblogin() {
        super("LIBRARIAN LOGIN");
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("home.jpg")).getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        libuserTF = new javax.swing.JTextField();
        libloginBTN = new javax.swing.JButton();
        hmBTN = new javax.swing.JButton();
        libpasTF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel1.setText("LIBRARIAN LOGIN");

        jLabel2.setText("USERNAME");

        jLabel3.setText("PASSWORD");

        libloginBTN.setText("Log In");
        libloginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libloginBTNActionPerformed(evt);
            }
        });

        hmBTN.setText("Home");
        hmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(libloginBTN)
                        .addGap(21, 21, 21)
                        .addComponent(hmBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(libpasTF)
                            .addComponent(libuserTF, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libuserTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(libpasTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hmBTN)
                    .addComponent(libloginBTN))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmBTNActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_hmBTNActionPerformed

    private void libloginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libloginBTNActionPerformed
        // TODO add your handling code here:
          try
        {
            int flag=0;
        Connection conn=ConnectionProvider.getConnection();
        Statement stmt=conn.createStatement();
        ResultSet rs=stmt.executeQuery("Select * from librarian");
        String aduser=libuserTF.getText();
        String pass=libpasTF.getText();
        while(rs.next())
        {
            String uuid=rs.getString("username");
            String ppwd=rs.getString("password");
            if(uuid.equals(aduser) && ppwd.equals(pass))
            {
                JOptionPane.showMessageDialog(null,"LOGIN SUCCESSFUL!!!!!");
                new librarian().setVisible(true);
                this.setVisible(false);
                flag=1;
            }
        }
        if(flag==0)
            {
                JOptionPane.showMessageDialog(null,"LOGIN OR PASSWORD WRONG!! PLEASE TRY AGAIN");
                libuserTF.setText("");
                libpasTF.setText("");
            }
        rs.close();
        conn.close();
        stmt.close();
        }
       

        
         catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_libloginBTNActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new liblogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hmBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton libloginBTN;
    private javax.swing.JPasswordField libpasTF;
    private javax.swing.JTextField libuserTF;
    // End of variables declaration//GEN-END:variables

}
